// Code generated by go generate; DO NOT EDIT.

package gtime

import (
  "database/sql/driver"
  "database/sql"
)

func init () {
  var _ = []driver.Valuer{
    TimeANSIC{},
    TimeUnixDate{},
    TimeRubyDate{},
    TimeRFC822{},
    TimeRFC822Z{},
    TimeRFC850{},
    TimeRFC1123{},
    TimeRFC1123Z{},
    TimeRFC3339{},
    TimeRFC3339Nano{},
    TimeKitchen{},
    TimeStamp{},
    TimeStampMilli{},
    TimeStampMicro{},
    TimeStampNano{},
    TimeDateTime{},
    TimeDateOnly{},
    TimeTimeOnly{},
  }

  var _ = []sql.Scanner{
    &TimeANSIC{},
    &TimeUnixDate{},
    &TimeRubyDate{},
    &TimeRFC822{},
    &TimeRFC822Z{},
    &TimeRFC850{},
    &TimeRFC1123{},
    &TimeRFC1123Z{},
    &TimeRFC3339{},
    &TimeRFC3339Nano{},
    &TimeKitchen{},
    &TimeStamp{},
    &TimeStampMilli{},
    &TimeStampMicro{},
    &TimeStampNano{},
    &TimeDateTime{},
    &TimeDateOnly{},
    &TimeTimeOnly{},
  }
}
